stages:
- prebuild
- build
- test
- update-static-files
- package
- sync
- deploy

workflow:
  # This workflow section prevents branch and merge request pipelines from
  # being created at the same time avoiding duplicate pipelines:
  # - if: $CI_PIPELINE_SOURCE == "merge_request_event" -> Create pipelines for open merge requests
  # - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
  #   ->  Do not create branch pipelines for open merge requests on push events but allow all other events (e.g.
  #       pipeline trigger, API calls, etc.)
  # - when: always -> Create all other pipeline types as usual
  # Using workflow rules also ensures that all jobs are included in both branch and merge request pipelines
  # See <https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines>
  # for more information
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
    when: never
  - when: always

include:
- local: "/.gitlab-ci/build-arch.yml"
- local: "/.gitlab-ci/build-binary-builder.yml"
- local: "/.gitlab-ci/build-centos.yml"
- local: "/.gitlab-ci/build-darwin.yml"
- local: "/.gitlab-ci/build-debian.yml"
- local: "/.gitlab-ci/build-emscripten.yml"
- local: "/.gitlab-ci/build-freebsd.yml"
- local: "/.gitlab-ci/build-ubuntu.yml"
- local: "/.gitlab-ci/build-windows.yml"
- local: "/.gitlab-ci/test.yml"
- local: "/.gitlab-ci/test-emscripten.yml"
- local: "/.gitlab-ci/test-ubuntu.yml"
- local: "/.gitlab-ci/update-static-files.yml"
- local: "/.gitlab-ci/package.yml"
- local: "/.gitlab-ci/sync.yml"
- local: "/.gitlab-ci/deploy.yml"

tag-type-check:
  stage: prebuild
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/deploy
  only:
  - tags@Scientific-IT-Systems/gr
  script:
  - test `git cat-file -t $CI_COMMIT_TAG` = "tag"
