freebsd-self-contained:
  stage: build
  image: freebsd:13-gr-build
  tags:
  - libvirt
  script:
  - export CPATH="/usr/local/include"
  - export LIBRARY_PATH="/usr/local/lib"
  - gmake -C 3rdparty default extras GRDIR=/usr/local/gr MAKE=gmake
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=ON
  - cmake --build build
  - DESTDIR="$(pwd)/install" cmake --install build
  - mv ./install/usr/local/gr ./artifacts-freebsd13
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-freebsd13/
