arch-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/arch-self-contained
  script:
  - make -C 3rdparty default extras
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DGR_USE_BUNDLED_LIBRARIES=ON -DCMAKE_INSTALL_LIBDIR=${CI_PROJECT_DIR}/install/lib
  - make
  - make install
  - cd ..
  - mv install artifacts-arch
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-arch/

arch-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/arch-system-dependencies
  script:
  - pacman -Sy
  - pacman -S --noconfirm --needed qhull
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DGR_USE_BUNDLED_LIBRARIES=OFF
  - make
