centos7-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-self-contained
  script:
  - source /opt/rh/devtoolset-8/enable
  - make -C 3rdparty default extras
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=ON
      -DCMAKE_INSTALL_LIBDIR="${CI_PROJECT_DIR}/install/lib"
  - cmake --build build
  - DESTDIR="${CI_PROJECT_DIR}/install"
    cmake --install build
  - mv ./install/usr/local/gr ./artifacts-centos7
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos7/

centos7-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-system-dependencies
  before_script:
  - yum install -y libjpeg-turbo-devel libtiff-devel bzip2-devel # TODO: Put these into the build images
  script:
  - source /opt/rh/devtoolset-8/enable
  - make -C 3rdparty default TARGETS="qhull"
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DCMAKE_FIND_ROOT_PATH="${CI_PROJECT_DIR}/3rdparty/build"
  - cmake --build build

centos7-32bit-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-32bit-self-contained
  script:
  - source /opt/gcc-8.5.0/enable
  - make -C 3rdparty default extras
      THEORA_EXTRA_CONFIGURE_FLAGS=--disable-asm
      OPENH264_EXTRA_MAKE_FLAGS=ARCH=i386
  - LDFLAGS="-static-libstdc++ -static-libgcc"
    cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=ON
  - cmake --build build
  - DESTDIR="${CI_PROJECT_DIR}/install"
    cmake --install build
  - mv ./install/usr/local/gr ./artifacts-centos7-32bit
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos7-32bit/

centos7-32bit-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-32bit-system-dependencies
  before_script:
  - yum install -y libtiff-devel bzip2-devel
  script:
  - source /opt/gcc-8.5.0/enable
  - make -C 3rdparty default TARGETS="qhull"
  - LDFLAGS="-static-libstdc++ -static-libgcc"
    cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DCMAKE_FIND_ROOT_PATH="${CI_PROJECT_DIR}/3rdparty/build"
  - cmake --build build
