ubuntu-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/ubuntu-self-contained
  script:
  - make -C 3rdparty default extras
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=ON
  - cmake --build build
  - DESTDIR="${CI_PROJECT_DIR}/install"
    cmake --install build
  - mv ./install/usr/local/gr ./artifacts-ubuntu2004
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-ubuntu2004/

ubuntu-self-contained-debug:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/ubuntu-self-contained
  script:
  - make -C 3rdparty default extras
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Debug
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=ON
      -DGR_BUILD_DEMOS=ON
      -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS"
  - cmake --build build
  - DESTDIR="${CI_PROJECT_DIR}/install"
    cmake --install build
  - install ./build/libGRM_int.so ./install/usr/local/gr/lib/
  - mv ./install/usr/local/gr artifacts-ubuntu2004
  - mv build/grm_test_internal_api ./
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-ubuntu2004/
    - grm_test_internal_api/

ubuntu-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/ubuntu-system-dependencies
  before_script:
  - apt-get update
  - apt-get install -y libqhull-dev libbz2-dev libjpeg-turbo8-dev libavdevice-dev libtheora-dev libogg-dev libvpx-dev libfreetype6-dev
  script:
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=OFF
  - cmake --build build
