emscripten:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
  - source /emsdk/emsdk_env.sh
  - emmake make -C 3rdparty default
  - emmake make
      -C 3rdparty/xerces-c
      XERCES_C_EXTRA_CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"
      libxerces-c.a
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DGR_USE_BUNDLED_LIBRARIES=ON
      -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
  - cmake --build build
  - mkdir artifacts-js
  - mv build/gr.js artifacts-js/
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-js/
