arch-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/arch-self-contained
  script:
  - make -C 3rdparty default extras
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=ON
  - cmake --build build
  - DESTDIR="${CI_PROJECT_DIR}/install"
    cmake --install build
  - mv ./install/usr/local/gr ./artifacts-arch
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-arch/

arch-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/arch-system-dependencies
  before_script:
  - pacman -Sy
  - pacman -S --noconfirm --needed qhull
  script:
  - cmake
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=/usr/local/gr
      -DGR_USE_BUNDLED_LIBRARIES=OFF
  - cmake --build build
