ubuntu-cmake-self-contained-test-c:
  stage: test
  image: iffregistry.fz-juelich.de/scientific-it-systems/gr-test/c-testing
  needs:
  - ubuntu-cmake-self-contained-debug
  script:
  - export GRDIR=`pwd`/artifacts-ubuntu2004-cmake/
  - export GR3_NUM_THREADS=4
  - export GRM_VALIDATE=yes
  - export TERM=ansi
  - export CLICOLOR_FORCE=1
  - gr_test c `pwd`/test_result/
  artifacts:
    paths:
    - test_result/
    when: always

ubuntu-cmake-self-contained-test-cpp:
  stage: test
  image: iffregistry.fz-juelich.de/scientific-it-systems/gr-test/cpp-testing
  needs:
  - ubuntu-cmake-self-contained-debug
  script:
  - export GRDIR=`pwd`/artifacts-ubuntu2004-cmake/
  - export GR3_NUM_THREADS=4
  - export GRM_VALIDATE=yes
  - export TERM=ansi
  - export CLICOLOR_FORCE=1
  - gr_test cpp `pwd`/test_result/
  artifacts:
    paths:
    - test_result/
    when: always

ubuntu-cmake-self-contained-test-grplot:
  stage: test
  image: iffregistry.fz-juelich.de/scientific-it-systems/gr-test/grplot-testing
  needs:
  - ubuntu-cmake-self-contained-debug
  script:
  - export GRDIR=`pwd`/artifacts-ubuntu2004-cmake/
  - export GR3_NUM_THREADS=4
  - export GRM_VALIDATE=yes
  - export LD_LIBRARY_PATH=$GRDIR/lib
  - export PATH=$GRDIR/bin/:$PATH
  - export TERM=ansi
  - export CLICOLOR_FORCE=1
  - gr_test grplot `pwd`/test_result/
  artifacts:
    paths:
    - test_result/
    when: always

ubuntu-cmake-self-contained-test-grm-internal:
  stage: test
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/ubuntu-self-contained
  needs:
  - ubuntu-cmake-self-contained-debug
  script:
  - export GRDIR=`pwd`/artifacts-ubuntu2004-cmake/
  - export GR3_NUM_THREADS=4
  - export LD_LIBRARY_PATH=`pwd`/artifacts-ubuntu2004-cmake/lib
  - export TERM=ansi
  - export CLICOLOR_FORCE=1
  - for f in grm_test_internal_api/*; do
      [[ -f "$f" && -x "$f" ]] || continue;
      printf "\n\e[1mRunning \"%s\":\e[0m\n" "$f";
      $f 2>&1 || exit 1;
    done
  artifacts:
    paths:
    - test_result/
    when: always
